import Navbar from './components/navbar'
import './globals.css'
import { NextAuthProvider } from './providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        {/* @ts-expect-error Async Server Component*/}
        <Navbar />
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
